---

- name: Include distribution-specific variables
  ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"

- name: Snmpd package install
  ansible.builtin.package: name={{ snmpd_packages }} state=present
  when: ansible_system == 'Linux'
  register: pkg_result
  until: pkg_result is success

- name: Snmpd client install
  ansible.builtin.package: name={{ snmp_packages }} state=present
  when: snmpd_with_client
  register: pkg_result
  until: pkg_result is success

- import_tasks: snmpd.yml
  when: ansible_system == 'Linux'

- import_tasks: snmpd-darwin.yml
  when: ansible_system == 'Darwin'

- import_tasks: openbsd.yml
  when: ansible_system == 'OpenBSD'
