---

## FIXME! should install macports when not existing
- stat: path=/opt/local/var/macports
  register: macportsdir
- name: darwin | Macports net-snmp package
  macports: name={{ item }} state=present update_cache=yes
  with_items:
    - net-snmp
  when: macportsdir.stat.exists

- name: ensure config directory exists
  file: dest=/opt/local/etc/snmp state=directory mode=0755
- stat: path=/opt/local/etc/snmp/snmpd.conf
  register: nconf
- name: darwin | configure snmpd
  template: src=snmpd.conf.j2 dest=/opt/local/etc/snmp/snmpd.conf mode=0644 backup=yes
  notify:
    - restart snmpd - darwin

