---

## FIXME! should install macports when not existing
- name: Check if macports is present
  ansible.builtin.stat:
    path: /opt/local/var/macports
  register: macportsdir
- name: Darwin | Macports net-snmp package
  community.general.macports:
    name: net-snmp
    state: present
    update_cache: yes
  when: macportsdir.stat.exists
  register: pkg_result
  until: pkg_result is success

- name: Ensure config directory exists
  ansible.builtin.file:
    dest: /opt/local/etc/snmp
    state: directory
    mode: '0755'
- name: Check if macports snmpd.conf exists
  ansible.builtin.stat:
    path: /opt/local/etc/snmp/snmpd.conf
  register: nconf
- name: Darwin | configure snmpd
  ansible.builtin.template:
    src: snmpd.conf.j2
    dest: /opt/local/etc/snmp/snmpd.conf
    mode: '0644'
    backup: yes
  notify:
    - Restart snmpd - darwin
