---

- name: Update snmpd configuration
  template:
    src: snmpd.conf.j2
    dest: '/etc/snmp/snmpd.conf'
    mode: 0640
    backup: yes
  notify:
    - restart snmpd

## https://bugs.launchpad.net/ubuntu/+source/net-snmp/+bug/1246347  "error on subcontainer ‘ia_addr’ insert (-1)"
- name: suppress buggy snmpd error messages
  replace: dest=/etc/default/snmpd regexp='-Lsd' replace='-LS6d' backup=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  notify:
    - restart snmpd

- name: restrict snmpd with hosts.deny
  lineinfile: dest=/etc/hosts.deny line='snmpd:ALL' backup=yes create=yes
- name: restrict snmpd with hosts.allow
  lineinfile: dest=/etc/hosts.allow line="snmpd:{{ item }}" backup=yes create=yes
  with_items: "{{ snmpd_clients }}"

- name: ensure service is enabled and started
  service: name=snmpd state=started enabled=yes

